# Generated by Django 3.2.8 on 2023-03-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='updare',
        ),
        migrations.AddField(
            model_name='todo',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
