version: '3.1'
services:
  db:
    image: postgres:14
    privileged: true
    restart: always
    ports:
      - 5432:5432
    environment:
        POSTGRES_USER: dilbazi12
        POSTGRES_PASSWORD: 1
        POSTGRES_DB: db

  backend:
    build: ./backend
    privileged: true
    ports:
      - 8080:8080
    command:
      bash -c "./settings/wait_postgres.sh db 
      python3 manage.py migrate &&
      
      python3 manage.py runserver 0.0.0.0:8080"





