version: '3.1'
services:
  db:
    image: postgres:14
    privileged: true
    restart: always
    ports:
      - 5432:5432
    environment:
        POSTGRES_USER: todo
        POSTGRES_PASSWORD: todo
        POSTGRES_DB: db
  adminer:
    image: adminer:4.7.8-standalone
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db



