# Generated by Django 3.2.8 on 2023-03-31 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todo_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='deleted',
        ),
    ]
